name: Rubocop

on: push

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@master
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: |
          bundle exec rubocop
